- src/documentBuilder.spec.ts
- src/documentBuilder.ts
Previously, calling `withAllowedPermissions` and `withDeniedPermissions` would replace the previous permission set, instead of adding/concatenating.
This will be useful for CLI push commands, among others.
https://coveord.atlassian.net/browse/CDX-486
> feat: support calling permissions function multiple time

- src/documentBuilder.spec.ts
- src/documentBuilder.ts
The limit for `permanentid` in the index is actually 60 characters. hashlib.sha256() is generating a 64-character hash. 
Rather than simply truncating it, I am proposing the default algorithm to generate permanentid in the index: `md5[:30]+sha1[:30]`
> feat(permanentid): replace sha256 by md5(30)+sha1(30)

- src/environment.ts
- src/index.ts
- src/source.spec.ts
- src/source.ts
This PR adds an option to specify the region when creating the source instance.
If not specified, the US region will be selected.
Following the issue: #87
> feat: support different regions

- src/fieldAnalyser/fieldAnalyser.ts
- src/source.ts
Adding a "Field Analyser" module right before initiating the push.
This module will be responsible of creating the missing fields with the right type, but also detecting type inconsistencies across batch(es) to be sent.
If type inconsistencies are detected, a prompt or any other process requiring user intervention will be put in place... or a flag allowing the SDK to choose the most probable type based on the documents.
> feat: add `FieldAnalyser` class

- src/errors/privilegeError.ts
- src/fieldAnalyser/fieldAnalyser.spec.ts
- src/fieldAnalyser/fieldAnalyser.ts
- src/fieldAnalyser/fieldUtils.ts
- src/fieldAnalyser/fieldsUtils.spec.ts
- src/interfaces.ts
- src/source/catalog.spec.ts
- src/source/catalog.stream.spec.ts
- src/source/push.spec.ts
- src/validation/preconditions/apiKeyPrivilege.spec.ts
- src/validation/preconditions/apiKeyPrivilege.ts
- src/validation/preconditions/platformPrivilege.ts
Whenever the API key does not have the required privileges, the SDK returns an error message leaving the user without information on the next steps.
This will happen if the user creates a Push or Catalog source via the Admin UI and uses the generated API key in the SDK.
Since the source creation generates an API with the minimum privileges, it will lack the privileges to list and create fields (which are required by the FieldAnalyser).
So instead of returning the API error message, we check if API key has the required privilege to perform the following API call.
> feat: provide better info on missing API key privileges

- src/fieldAnalyser/fieldAnalyser.spec.ts
- src/fieldAnalyser/fieldAnalyser.ts
- src/fieldAnalyser/typeUtils.spec.ts
- src/fieldAnalyser/typeUtils.ts
There was an issue with the numeric type "evolution". 
When the FieldAnalyser was detecting that a field that was previously defined as Integer but now detected as float, then the more englobing type (float) was chosen.
However, the opposite scenario was causing an issue rather than sticking to the most englobing type.
> fix: numeric type evolution

- src/source/batchUploadDocumentsFromFile.ts
- src/source/catalog.ts
- src/source/documentUploader.ts
- src/source/push.ts
- src/validation/preconditions/apiKeyPrivilege.spec.ts
No change in functionality.
Simply move the upload methods into the same file (`documentUploader.ts`) to have a single place where default upload options are defined.
> chore: centralize default upload options

- tsconfig.json
`importHelper` is not really needed in our case, let's remove it.
> fix(deps): remove tslib implicit dependency

- jest.config.js
We run the UT on src, not dist.
> chore(jest): ignore `dist` for ut

- src/help/__snapshots__/fileContainer.spec.ts.snap
- src/help/fileConsumer.ts
- src/help/fileContainer.spec.ts
- src/help/fileContainer.ts
- src/source/catalog.spec.ts
- src/source/catalog.stream.spec.ts
- src/source/push.spec.ts
I removed the maximum body limit of 5KB. It was set to 5KB instead of 5MB. This was causing requests larger than 5KB to return an error.
The request size limits of the Push API could change at any time without prior notice, so it does not make sense for the SDK to impose a lower limit that could be deprecated in the future. That's why I would simply set the `maxBodyLength` value to the limit of a file container (256MB). As long as the limit is bigger than the document chunk size.
> fix: inscrease axios body size

- src/source/catalog.stream.spec.ts
- src/source/documentUploader.ts
The `catalogSource#batchStreamDocuments`   was not running the preUpload.
Consequence: No stream was opened before indexation
> fix(stream): add missing preUpload

- samples/pushDocumentWithMetadata.ts
- src/document.ts
- src/documentBuilder.spec.ts
- src/fieldAnalyser/typeUtils.spec.ts
- src/fieldAnalyser/typeUtils.ts
Support [dictionary fields](https://docs.coveo.com/en/2036/index-content/about-fields#index-dictionary-fields), which can be used in commerce implementations. 
* Update `MetadataValue` type to support objects
* Detect most englobing type of a dictionary field. If the dictionary is inconsistent, the String type will be used as the most englobing one.
> feat(fieldanalyser): support dictionary fields

- src/help/fileConsumer.ts
- src/help/generator.spec.ts
- src/help/generator.ts
- src/source/batchUploadDocumentsFromFile.ts
- src/validation/parseFile.spec.ts
- src/validation/parseFile.ts
The `parseAndGetDocumentBuilderFromJSONDocument` could accept an async callback that was executed every time the generator was iterating over a new document.
However, the generator was not waiting for the callback resolution to iterate over the next value... therefore loading in memory all the unresolved promises.
> fix: memory leak on async callback

- src/fieldAnalyser/fieldAnalyser.ts
- src/help/fileConsumer.ts
- src/help/generator.spec.ts
- src/help/generator.ts
- src/source/batchUploadDocumentsFromFile.ts
- src/validation/parseFile.spec.ts
- src/validation/parseFile.ts
No need to check for the "write field privilege" since the FieldAnalyser does not create fields.
This was firing a request every time a document was added to the analyser.
> fix: remove precondition check

- package-lock.json
- package.json
Cannot consume axios typescript types using CommonJS since Axios released v1.
This impacts the CLI and any clients consuming the push-api-client within a Typescript project.
Until Axios releases a official version, we will be using the alpha in which the issue has been fixed.
> chore(deps): update axios to alpha version

- fixLock.mjs
- package-lock.json
- package.json
This will ensure the error we see in renovate PR #233 doesn't happen again.
This is caused by `standard-version` not playing nice with the 'self-import' that we use for the sample.
This is a bit 🩹 but the other solution is a bit heavy handed: switch to semantic-monorepo-tools.
Will keep that for the move to coveo/sdk,js
> chore(cd): ensure we update package-lock.json on release

- .github/workflows/release.yml
Bump actions-gh-pages to specific 3.9 hash to comply with CSEC's policies on GHAs
https://coveord.atlassian.net/browse/CSEC-18897
> CSEC-18897 bump peaceiris/actions-gh-pages to 3.9 via hash

- src/securityIdentityBuilder.spec.ts
- src/securityIdentityBuilder.ts
When the security provider was not specified during the permission creation, the marshalled JSON sent to the API contained `undefined` as a value for the securityProvider.
[CDX](https://coveord.atlassian.net/browse/CDX-1276)
> fix: discard undefined security provider

- samples/pushDocumentWithPermissions.ts
- src/__snapshots__/permissionSetBuilder.spec.ts.snap
- src/document.ts
- src/documentBuilder.ts
- src/index.ts
- src/permissionSetBuilder.spec.ts
- src/permissionSetBuilder.ts
- src/securityIdentityBuilder.spec.ts
- src/securityIdentityBuilder.ts
Create a Builder class to define document permissions. This class will be utilized in CDX-1278 **(TODO: add PR link)**.
Simply adding allowed and denied securities to the document is not enough to support the permission models supported by the API.
- [Simple Permission Model Definition Examples](https://docs.coveo.com/en/107/index-content/simple-permission-model-definition-examples).
- [Complex Permission Model Definition Example](https://docs.coveo.com/en/25/index-content/complex-permission-model-definition-example)
> chore: create `PermissionSetBuilder` class

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- fixLock.mjs
- package-lock.json
- package.json
- samples/json/sample.json
- src/APICore.ts
- src/help/__snapshots__/fileContainer.spec.ts.snap
- src/help/fileConsumer.spec.ts
- src/help/fileConsumer.ts
- src/help/fileContainer.spec.ts
- src/help/fileContainer.ts
- src/interfaces.ts
- src/source/catalog.ts
- src/source/documentUploader.spec.ts
- src/source/documentUploader.ts
- src/source/push.spec.ts
- src/source/push.ts
- src/source/securityIdenty.ts
- src/uploadStrategy/fileContainerStrategy.spec.ts
- src/uploadStrategy/fileContainerStrategy.ts
- src/uploadStrategy/strategy.ts
- src/uploadStrategy/streamChunkStrategy.spec.ts
- src/uploadStrategy/streamChunkStrategy.ts
- tsconfig.json
- chore: replaced old polyfill by new one.
- chore!: drop support for Node 14
- feat!: replace axios by fetch
- refactor: moved serialization (i.e. `.data` with axios, `.json()`) to `put/post/get` methods
For the error handling, I based myself on https://web.dev/fetch-api-error-handling/
- Drop support for Node14
- Return types changes from `AxiosResponse` to `Response` at a few places
- `uploadContentToFileContainer()` now throws [AggretateError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError)
> feat!: replace axios by fetch

- .github/workflows/release.yml
- package.json
Recursive git tag/git push tags. It was 'fun'.
When we run `npm publish`, we run `prepublishOnly`, which trigger `npm release`, which start `release.mjs`.
But this https://github.com/coveo/push-api-client.js/blob/484712d544d36104b5032b3d5d1bdd97dbfbe06e/release.mjs#L91  essentially do `npm publish`. Which start the loops again. And before we do a publish, well we do this
https://github.com/coveo/push-api-client.js/blob/484712d544d36104b5032b3d5d1bdd97dbfbe06e/release.mjs#L79-L88
So until we trip some recursion limit or whatever, well it keep on bump, commit, tag, and so forth.
> chore: do not npm publish directly

- .prettierignore
- CHANGELOG.md
- samples/tsconfig.json
- src/documentBuilder.spec.ts
- src/documentBuilder.ts
- src/help/__snapshots__/fileContainer.spec.ts.snap
Apply a lower-case transformation to the **permanent Id** since it is case-sensitive.
More info in this [Discuss topic](https://discuss.coveo.com/t/support-00095229-push-source-with-specific-permanentid-values).
Waiting until the backend team reply to know if we should apply that lower-case transformation to every keys in the payload or if this is a special case.
> fix: make permanentid lower-case

- .github/workflows/build.yml
- .github/workflows/release.yml
- package-lock.json
So, before, the release workflow was triggered every time the build one was completed, regardless of what triggered the latter.
This was not the intended behavior.
Now, instead of having release 'listening on' the completion of build, build is calling release when its been triggered by a push to main
> chore: trigger CD from CI workflow

- .github/workflows/build.yml
- .github/workflows/release.yml
There's either a documentation gap or a bug in GHA, I described the issue here
https://github.com/community/community/discussions/47583
So in the meantime, I'm reverting the changes and adding a branch filter based on:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#limiting-your-workflow-to-run-based-on-branches
Because it's hard to have certainty it won't trigger a resonance release cascade, I enabled the Required Reviewer Environment Protection Rule on CD for the time being.
> chore: replace call by run

- package-lock.json
- package.json
- src/APICore.spec.ts
- src/APICore.ts
- src/errors/__snapshots__/fetchError.spec.ts.snap
- src/errors/fetchError.spec.ts
- src/errors/fetchError.ts
- src/errors/index.ts
- src/errors/throttleError.spec.ts
- src/errors/throttleError.ts
Handle this:
> The Promise returned from fetch() won't reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, as soon as the server responds with headers, the Promise will resolve normally (with the [ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) property of the response set to false if the response isn't in the range 200–299), and it will only reject on network failure or if anything prevented the request from completing.
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
- Add FetchError
- Add ThrottleError
- Rework retry cb for exp-backoff
> fix(fetch): throw when request is nok

- src/APICore.ts
https://coveord.atlassian.net/browse/KIT-2802
This is a fairly quick one. Pascal Doyon requested that we include some basic client information in the 'User-Agent' request header, so now said header will include `CoveoNodeJSSDK/<VERSION>`.
https://docs.google.com/document/d/1FM3KDK8jlsGSz2IgtXLYfqz_xjvCFWXsSmHYlVf0rfs/edit
I was unable to get the current package version any way other than reading the package.json file through a `require`, which I'm not super happy about. It appears to be working as expected when running the tests, so I'll leave it unless anyone has any very strong opinions about it 😅 
Moreover, I couldn't find a good way to test that the version was correct unless I used the same "trick" within the test file, which I don't believe is particularly useful.
> chore: include client details in header

- release.mjs
The [create release workflow](https://github.com/coveo/push-api-client.js/actions/workflows/release.yml) is currently failing, which prevents [the node 22 support changes](https://github.com/coveo/push-api-client.js/commit/151d9c90965c9ec8751b19757c6bdfa4ce2f0eae) to come through.
If fails on the following [`TypeError: Cannot read properties of undefined (reading 'whatBump')`](https://github.com/coveo/push-api-client.js/actions/runs/11594306860/job/32280246725#step:10:117)
Looking at [`conventional-changelor-angular`'s source code](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/src/index.js#L9), we can see that `whatBump` is exposed directly on the default export, and that `recommendedBumpOpts` does not exist anymore.
> build(release): fix release workflow
